<a href="https://colab.research.google.com/github/LucasColas/AI-Game-Side-Scroller/blob/master/LR%20Multiple%20variables/Test_LR_Multiple_var.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multiple Linear Regression  

---



In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
from sklearn import preprocessing
from sklearn import model_selection
from sklearn import linear_model


In [2]:
from google.colab import files
import io

dataset = files.upload()

Saving data_csv.csv to data_csv.csv


In [3]:
df = pd.read_csv(io.BytesIO(dataset['data_csv.csv']))

In [4]:
df #Load

Date    SP500  Dividend  ...  Real Dividend  Real Earnings   PE10
0     1871-01-01     4.44      0.26  ...           5.21           8.02    NaN
1     1871-02-01     4.50      0.26  ...           5.06           7.78    NaN
2     1871-03-01     4.61      0.26  ...           4.98           7.67    NaN
3     1871-04-01     4.74      0.26  ...           5.17           7.96    NaN
4     1871-05-01     4.86      0.26  ...           5.29           8.14    NaN
...          ...      ...       ...  ...            ...            ...    ...
1763  2017-12-01  2664.34     48.93  ...          49.59         111.36  32.09
1764  2018-01-01  2789.80     49.29  ...          49.68            NaN  33.31
1765  2018-02-01  2705.16     49.64  ...          49.81            NaN  32.12
1766  2018-03-01  2702.77     50.00  ...          50.06            NaN  31.99
1767  2018-04-01  2642.19       NaN  ...            NaN            NaN  31.19

[1768 rows x 10 columns]

In [5]:
dataset = df.iloc[948:1768,0:10]

In [6]:
dataset

Date    SP500  Dividend  ...  Real Dividend  Real Earnings   PE10
948   1950-01-01    16.88      1.15  ...          12.23          24.84  10.75
949   1950-02-01    17.21      1.16  ...          12.33          25.02  10.91
950   1950-03-01    17.35      1.17  ...          12.39          25.09  10.91
951   1950-04-01    17.84      1.18  ...          12.49          25.69  11.18
952   1950-05-01    18.44      1.19  ...          12.54          26.18  11.46
...          ...      ...       ...  ...            ...            ...    ...
1763  2017-12-01  2664.34     48.93  ...          49.59         111.36  32.09
1764  2018-01-01  2789.80     49.29  ...          49.68            NaN  33.31
1765  2018-02-01  2705.16     49.64  ...          49.81            NaN  32.12
1766  2018-03-01  2702.77     50.00  ...          50.06            NaN  31.99
1767  2018-04-01  2642.19       NaN  ...            NaN            NaN  31.19

[820 rows x 10 columns]

In [7]:
dataset.head()

Date  SP500  Dividend  ...  Real Dividend  Real Earnings   PE10
948  1950-01-01  16.88      1.15  ...          12.23          24.84  10.75
949  1950-02-01  17.21      1.16  ...          12.33          25.02  10.91
950  1950-03-01  17.35      1.17  ...          12.39          25.09  10.91
951  1950-04-01  17.84      1.18  ...          12.49          25.69  11.18
952  1950-05-01  18.44      1.19  ...          12.54          26.18  11.46

[5 rows x 10 columns]

In [8]:
data_frame = dataset[['Date', 'Long Interest Rate', 'Real Price', 'Real Dividend']]

In [9]:
data_frame

Date  Long Interest Rate  Real Price  Real Dividend
948   1950-01-01                2.32      179.46          12.23
949   1950-02-01                2.34      182.96          12.33
950   1950-03-01                2.36      183.67          12.39
951   1950-04-01                2.38      188.86          12.49
952   1950-05-01                2.40      194.39          12.54
...          ...                 ...         ...            ...
1763  2017-12-01                2.40     2700.13          49.59
1764  2018-01-01                2.58     2811.96          49.68
1765  2018-02-01                2.86     2714.34          49.81
1766  2018-03-01                2.84     2705.82          50.06
1767  2018-04-01                2.80     2642.19            NaN

[820 rows x 4 columns]

In [10]:
data_frame.isna().sum()

Date                  0
Long Interest Rate    0
Real Price            0
Real Dividend         1
dtype: int64

In [11]:
data_frame.fillna(method='ffill', inplace=True)
data_frame

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,


Date  Long Interest Rate  Real Price  Real Dividend
948   1950-01-01                2.32      179.46          12.23
949   1950-02-01                2.34      182.96          12.33
950   1950-03-01                2.36      183.67          12.39
951   1950-04-01                2.38      188.86          12.49
952   1950-05-01                2.40      194.39          12.54
...          ...                 ...         ...            ...
1763  2017-12-01                2.40     2700.13          49.59
1764  2018-01-01                2.58     2811.96          49.68
1765  2018-02-01                2.86     2714.34          49.81
1766  2018-03-01                2.84     2705.82          50.06
1767  2018-04-01                2.80     2642.19          50.06

[820 rows x 4 columns]

In [12]:
data_frame['Real Price Label'] = data_frame['Real Price'].shift(-3)
data_frame

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


Date  Long Interest Rate  ...  Real Dividend  Real Price Label
948   1950-01-01                2.32  ...          12.23            188.86
949   1950-02-01                2.34  ...          12.33            194.39
950   1950-03-01                2.36  ...          12.39            196.72
951   1950-04-01                2.38  ...          12.49            180.17
952   1950-05-01                2.40  ...          12.54            189.48
...          ...                 ...  ...            ...               ...
1763  2017-12-01                2.40  ...          49.59           2705.82
1764  2018-01-01                2.58  ...          49.68           2642.19
1765  2018-02-01                2.86  ...          49.81               NaN
1766  2018-03-01                2.84  ...          50.06               NaN
1767  2018-04-01                2.80  ...          50.06               NaN

[820 rows x 5 columns]

In [13]:
features_temp = data_frame.drop("Date",1)
features = np.array(features_temp.drop('Real Price Label', 1))

scaled_features = preprocessing.scale(features)
scaled_features


array([[-1.17918844, -1.16779909, -1.29588611],
       [-1.17220065, -1.16202168, -1.28285017],
       [-1.16521287, -1.16084969, -1.2750286 ],
       ...,
       [-0.99051829,  3.01650245,  3.60302319],
       [-0.99750607,  3.00243857,  3.63561306],
       [-1.01148164,  2.89740516,  3.63561306]])

In [26]:
scaled_features_l_3 = scaled_features[-3:]
print("scaled features latest 3 : ", scaled_features_l_3)
scaled_features = scaled_features[:-3]
scaled_features

scaled features latest 3 :  [[-1.16870676  2.8721661   3.53653985]
 [-1.1512373   2.99304615  3.5743441 ]
 [-1.08834725  3.17764283  3.58607645]]


array([[-1.17918844, -1.16779909, -1.29588611],
       [-1.17220065, -1.16202168, -1.28285017],
       [-1.16521287, -1.16084969, -1.2750286 ],
       ...,
       [-1.21762124,  2.66170311,  3.45702057],
       [-1.22111514,  2.70117111,  3.46614573],
       [-1.16521287,  2.81107406,  3.50394998]])

In [15]:
data_frame.dropna(inplace=True)
data_frame

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


Date  Long Interest Rate  ...  Real Dividend  Real Price Label
948   1950-01-01                2.32  ...          12.23            188.86
949   1950-02-01                2.34  ...          12.33            194.39
950   1950-03-01                2.36  ...          12.39            196.72
951   1950-04-01                2.38  ...          12.49            180.17
952   1950-05-01                2.40  ...          12.54            189.48
...          ...                 ...  ...            ...               ...
1760  2017-09-01                2.20  ...          48.76           2700.13
1761  2017-10-01                2.36  ...          49.05           2811.96
1762  2017-11-01                2.35  ...          49.30           2714.34
1763  2017-12-01                2.40  ...          49.59           2705.82
1764  2018-01-01                2.58  ...          49.68           2642.19

[817 rows x 5 columns]

In [16]:
label = np.array(data_frame['Real Price Label'])
label

array([ 188.86,  194.39,  196.72,  180.17,  189.48,  195.36,  201.8 ,
        200.58,  197.37,  208.62,  213.87,  209.46,  212.26,  211.54,
        207.87,  211.54,  220.8 ,  224.76,  222.75,  214.92,  220.7 ,
        228.06,  225.61,  226.18,  224.66,  224.57,  229.85,  234.68,
        235.61,  231.87,  227.  ,  234.21,  243.66,  245.89,  243.8 ,
        244.11,  232.08,  232.43,  223.27,  226.44,  226.52,  216.12,
        221.8 ,  227.55,  230.61,  236.46,  241.66,  246.77,  257.57,
        266.83,  268.97,  279.83,  285.41,  293.18,  299.99,  311.74,
        327.22,  333.11,  344.25,  341.54,  353.33,  351.83,  372.23,
        397.97,  395.54,  411.81,  391.1 ,  417.48,  422.95,  411.58,
        414.19,  442.71,  446.27,  430.64,  425.  ,  444.78,  443.76,
        427.09,  420.09,  415.73,  420.38,  411.23,  392.07,  395.69,
        403.41,  417.4 ,  422.76,  428.25,  404.68,  388.26,  364.07,
        354.96,  354.78,  359.2 ,  360.43,  365.3 ,  366.02,  377.78,
        386.86,  396

In [18]:
(features_train, features_test, label_train, label_test) = model_selection.train_test_split(scaled_features, label, test_size=0.15, random_state = 7)


In [20]:
model = linear_model.LinearRegression()
model.fit(features_train, label_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
model.score(features_test, label_test)

0.9924279387756088

In [23]:
prediction = model.predict(features_test)
prediction

array([2050.62562984, 2212.0886232 , 2486.21092184, 1348.6560865 ,
       1759.46285818,  484.17021218, 1254.62942593,  241.31579757,
        328.9330409 ,  363.2335799 ,  368.42040733, 1572.37381026,
        571.24957908, 1684.78802698, 1825.42537344,  489.6826329 ,
       2084.21148657, 1508.75109481,  372.29828927,  556.58236675,
        312.37340087,  299.14679584,  678.11519433,  562.26769969,
        766.59447651,  276.44162675,  656.44702433, 1324.65616443,
        524.42072266, 1299.78849765, 1610.75177487,  683.76026458,
        713.31342175,  751.79182283,  584.6869921 ,  341.9156405 ,
       2054.34724246,  801.69054557,  501.3899695 ,  549.71365112,
        452.99257626,  426.70690318,  719.06439276,  600.48633078,
        352.0340646 ,  746.78077123,  343.5684728 ,  388.1186634 ,
        580.23533313,  387.18549893,  632.87200083,  322.89715879,
        528.426579  , 2090.76048825,  562.33541062,  360.95450889,
       1691.42194739,  225.0749296 , 1553.04507471,  653.61217

In [25]:
predict = model.predict(scaled_features_l_3)
predict

array([2752.47253433, 2744.80858144, 2682.76302154])